### ISSUE TITLE
Minus sign not available when editing numeric values 

### ISSUE THREAD

**Issue by dbarbier** [bjnortier/shapesmith.deprecated#11]
Hello,

-/+ keys are used to zoom out/in, but it would be nice if those keys were available when editing numeric values.  At the moment, my only solution is to copy/paste with mouse, which is not very convenient.

**Comment by bjnortier** [comment]
This is a bug - thanks for submitting! Will fix for 0.3.1

**Comment by bjnortier** [comment]
Ok fixed in master and cloud.shapesmith.net. If the mouse cursor is over the treeview on the left, it will accept +/- as input into the text fields. If the mouse cursor is over the 3D view, it will zoom. 

Alternatively, +/- should always go to the input if there is an active input field. What do you think?

**Comment by dbarbier** [comment]
Thanks, this is indeed much more convenient. Your question is difficult; I prefer the latter, but OTOH the current behavior is more powerful, one can still zoom in/out while a text input field is active.

**Comment by bjnortier** [comment]
Both have their advantages and drawbacks. I'll consider this issue closed for now.
